import type { GenerateResult, Answers } from '@/types';

export async function exportToPDF(result: GenerateResult, answers: Answers) {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const M = 20, W = 210, CW = W - M * 2;
  let y = M;

  const addPage = (need = 20) => { if (y + need > 280) { doc.addPage(); y = M; } };
  const write = (text: string, size = 11, style: 'normal'|'bold' = 'normal', color = '#1A1814') => {
    doc.setFontSize(size); doc.setFont('helvetica', style); doc.setTextColor(color);
    const lines = doc.splitTextToSize(text, CW);
    addPage(lines.length * (size * 0.4 + 2));
    doc.text(lines, M, y);
    y += lines.length * (size * 0.4 + 2);
  };

  // Header
  doc.setFillColor(26,24,20); doc.rect(0,0,W,40,'F');
  doc.setFontSize(22); doc.setFont('helvetica','bold'); doc.setTextColor('#F0D080');
  doc.text('PROFIT COMPASS', M, 18);
  doc.setFontSize(10); doc.setFont('helvetica','normal'); doc.setTextColor('#B8B6AF');
  doc.text('Your Personalized Online Income Roadmap', M, 28);
  doc.text(`Generated: ${new Date().toLocaleDateString('en-US',{dateStyle:'long'})}`, M, 36);
  y = 52;

  doc.setFontSize(12); doc.setFont('helvetica','bold'); doc.setTextColor('#1A1814');
  doc.text('YOUR PROFILE SUMMARY', M, y); y += 6;
  doc.setDrawColor(201,168,76); doc.setLineWidth(0.5); doc.line(M, y, W-M, y); y += 6;
  write(result.summary, 11, 'normal', '#4A4840'); y += 4;

  [['Time', answers.time||'—'],['Budget', answers.budget||'—'],['Goal', answers.goal||'—']].forEach(([l,v]) => {
    doc.setFontSize(9); doc.setFont('helvetica','bold'); doc.setTextColor('#8A6820');
    doc.text(`${l}: `, M, y);
    doc.setFont('helvetica','normal'); doc.setTextColor('#1A1814');
    doc.text(v, M + doc.getTextWidth(`${l}: `), y); y += 5;
  });
  y += 8;

  result.ideas.forEach((idea, i) => {
    addPage(60);
    doc.setFillColor(250,248,240); doc.rect(M, y-4, CW, 14, 'F');
    doc.setFontSize(13); doc.setFont('helvetica','bold'); doc.setTextColor('#1A1814');
    doc.text(`${i+1}. ${idea.title}`, M+3, y+5); y += 14;
    doc.setFontSize(9); doc.setFont('helvetica','bold'); doc.setTextColor('#1A5C35');
    doc.text(`$${idea.incomeMin?.toLocaleString()}–$${idea.incomeMax?.toLocaleString()}/mo  ·  ${idea.hoursPerWeek}  ·  ${idea.startupCost}`, M, y);
    y += 6;
    doc.setDrawColor(226,224,216); doc.setLineWidth(0.3); doc.line(M, y, W-M, y); y += 5;

    ['What it is|'+idea.blurb, 'Revenue model|'+idea.revenueModel, 'Skills needed|'+idea.requiredSkills].forEach(s => {
      const [label, content] = s.split('|');
      addPage(25);
      doc.setFontSize(8); doc.setFont('helvetica','bold'); doc.setTextColor('#8A6820');
      doc.text(label.toUpperCase(), M, y); y += 4;
      write(content, 10, 'normal', '#1A1814'); y += 3;
    });

    addPage(30); write('FIRST STEPS', 8, 'bold', '#8A6820'); y += 2;
    (idea.firstSteps||[]).forEach((step, si) => {
      addPage(10);
      doc.setFontSize(10); doc.setFont('helvetica','bold'); doc.setTextColor('#C9A84C');
      doc.text(`${si+1}.`, M, y);
      doc.setFont('helvetica','normal'); doc.setTextColor('#1A1814');
      const lines = doc.splitTextToSize(step, CW-8);
      doc.text(lines, M+6, y); y += lines.length * 5 + 2;
    });
    y += 4;

    if (idea.example) { write('EXAMPLE', 8, 'bold', '#8A6820'); y += 1; write(idea.example, 10); y += 3; }
    if (idea.pitfall) { write('PITFALL', 8, 'bold', '#8A6820'); y += 1; write(idea.pitfall, 10); y += 3; }

    y += 4; doc.setDrawColor(201,168,76); doc.setLineWidth(0.3); doc.line(M, y, W-M, y); y += 10;
  });

  doc.setFontSize(8); doc.setTextColor('#B8B6AF');
  doc.text('Generated by Profit Compass · Income estimates are projections, not guarantees.', M, 288);
  doc.save('profit-compass-ideas.pdf');
}
